/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_exercises_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise */
        get: operations["get_exercise_exercises__exercise_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exercise_id}/alternatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alternatives */
        get: operations["get_alternatives_exercises__exercise_id__alternatives_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State */
        get: operations["get_state_me_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/routine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Routine */
        get: operations["get_routine_me_routine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Today */
        get: operations["get_today_me_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/bodyweight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bodyweight */
        get: operations["get_bodyweight_me_bodyweight_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_me_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Export */
        get: operations["get_export_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Volume */
        get: operations["get_volume_me_volume_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Records */
        get: operations["get_records_me_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/routine/exercises/{rde_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Exercise */
        delete: operations["remove_exercise_me_routine_exercises__rde_id__delete"];
        options?: never;
        head?: never;
        /** Update Exercise */
        patch: operations["update_exercise_me_routine_exercises__rde_id__patch"];
        trace?: never;
    };
    "/me/routine/days/{day_id}/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Exercise */
        post: operations["add_exercise_me_routine_days__day_id__exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/routine/days/{day_id}/exercise-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder Exercises */
        put: operations["reorder_exercises_me_routine_days__day_id__exercise_order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/routine/days/{day_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename Day */
        patch: operations["rename_day_me_routine_days__day_id__patch"];
        trace?: never;
    };
    "/me/routine/day-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder Days */
        put: operations["reorder_days_me_routine_day_order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlternativeOut
         * @description A same-pattern swap candidate (spec §5.3). `substitution_count` is how
         *     often this user has already swapped the planned exercise for this one.
         */
        AlternativeOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            pattern: components["schemas"]["MovementPattern"];
            equipment: components["schemas"]["Equipment"];
            /** Media Url */
            media_url?: string | null;
            /**
             * Per Side
             * @default false
             */
            per_side: boolean;
            /** Substitution Count */
            substitution_count: number;
            /** Default Rest S */
            default_rest_s: number;
        };
        /** BodyWeightIn */
        BodyWeightIn: {
            /** Id */
            id: string;
            /**
             * Measured On
             * Format: date
             */
            measured_on: string;
            /** Weight Kg */
            weight_kg: number;
        };
        /** BodyWeightPoint */
        BodyWeightPoint: {
            /**
             * Measured On
             * Format: date
             */
            measured_on: string;
            /** Weight Kg */
            weight_kg: number;
        };
        /**
         * BodyWeightSummary
         * @description 7-day moving average is the only accionable value (spec §5.6); the raw
         *     latest is exposed only for the treadmill estimate (spec §5.5).
         */
        BodyWeightSummary: {
            /** Latest */
            latest: number | null;
            /** Avg7 */
            avg7: number | null;
            /** Delta Week */
            delta_week: number | null;
            /** Points */
            points: components["schemas"]["BodyWeightPoint"][];
        };
        /** DayRename */
        DayRename: {
            /** Name */
            name: string;
        };
        /**
         * Equipment
         * @enum {string}
         */
        Equipment: "barra" | "mancuernas" | "maquina" | "polea" | "peso_corporal";
        /** ExerciseAdd */
        ExerciseAdd: {
            /** Exercise Id */
            exercise_id: string;
            /**
             * Target Sets
             * @default 3
             */
            target_sets: number;
            /**
             * Rep Min
             * @default 8
             */
            rep_min: number;
            /**
             * Rep Max
             * @default 12
             */
            rep_max: number;
        };
        /** ExerciseOut */
        ExerciseOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            pattern: components["schemas"]["MovementPattern"];
            equipment: components["schemas"]["Equipment"];
            /** Media Url */
            media_url?: string | null;
            /**
             * Per Side
             * @default false
             */
            per_side: boolean;
            /** Description */
            description: string;
            /** Default Rest S */
            default_rest_s: number;
        };
        /** ExerciseSummary */
        ExerciseSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            pattern: components["schemas"]["MovementPattern"];
            equipment: components["schemas"]["Equipment"];
            /** Media Url */
            media_url?: string | null;
            /**
             * Per Side
             * @default false
             */
            per_side: boolean;
        };
        /** ExerciseUpdate */
        ExerciseUpdate: {
            /** Target Sets */
            target_sets: number;
            /** Rep Min */
            rep_min: number;
            /** Rep Max */
            rep_max: number;
            /** Rest S */
            rest_s: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginIn */
        LoginIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * LoginOut
         * @description Login also returns the JWT in the body so a native client (Capacitor) can
         *     store it and authenticate via `Authorization: Bearer`. Web keeps using the
         *     httpOnly cookie and ignores this field.
         */
        LoginOut: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Token */
            token: string;
        };
        /**
         * MovementPattern
         * @enum {string}
         */
        MovementPattern: "empuje_horizontal" | "empuje_vertical" | "tiron_horizontal" | "tiron_vertical" | "cuadriceps" | "cadena_posterior" | "gluteo" | "gemelo" | "deltoides_lateral" | "triceps" | "biceps" | "core";
        /** OrderBody */
        OrderBody: {
            /** Ids */
            ids: string[];
        };
        /**
         * RecordOut
         * @description Personal record per exercise: best estimated 1RM (Epley, spec §7.2).
         */
        RecordOut: {
            /** Exercise Id */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string;
            /** Weight Kg */
            weight_kg: number;
            /** Reps */
            reps: number;
            /** One Rm */
            one_rm: number;
            /**
             * Achieved On
             * Format: date
             */
            achieved_on: string;
        };
        /** RoutineDayExerciseOut */
        RoutineDayExerciseOut: {
            /** Id */
            id: string;
            /** Order Index */
            order_index: number;
            /** Target Sets */
            target_sets: number;
            /** Rep Min */
            rep_min: number;
            /** Rep Max */
            rep_max: number;
            /** Rest S */
            rest_s: number;
            exercise: components["schemas"]["ExerciseSummary"];
        };
        /** RoutineDayOut */
        RoutineDayOut: {
            /** Id */
            id: string;
            /** Position */
            position: number;
            /** Name */
            name: string;
            /** Suggested Dow */
            suggested_dow: number | null;
            /** Exercises */
            exercises: components["schemas"]["RoutineDayExerciseOut"][];
        };
        /** RoutineOut */
        RoutineOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Active */
            active: boolean;
            /** Days */
            days: components["schemas"]["RoutineDayOut"][];
        };
        /** SessionIn */
        SessionIn: {
            /** Id */
            id: string;
            /** Routine Day Id */
            routine_day_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** @default in_progress */
            status: components["schemas"]["SessionStatus"];
            /** Notes */
            notes?: string | null;
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: string;
            /** Routine Day Id */
            routine_day_id: string;
            /** Position */
            position: number;
            /** Day Name */
            day_name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            status: components["schemas"]["SessionStatus"];
            /** Notes */
            notes: string | null;
            /**
             * Set Count
             * @default 0
             */
            set_count: number;
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "in_progress" | "completed" | "abandoned";
        /** SetLogIn */
        SetLogIn: {
            /** Id */
            id: string;
            /** Session Id */
            session_id: string;
            /** Exercise Id */
            exercise_id: string;
            /** Planned Exercise Id */
            planned_exercise_id?: string | null;
            /** Set Number */
            set_number: number;
            /** Weight Kg */
            weight_kg: number;
            /** Reps */
            reps: number;
            /**
             * Voided
             * @default false
             */
            voided: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StateOut */
        StateOut: {
            /** Routine Id */
            routine_id: string;
            /** Next Position */
            next_position: number;
            /** Last Session At */
            last_session_at: string | null;
        };
        /** SyncEventOut */
        SyncEventOut: {
            /** Seq */
            seq: number;
            /** Entity */
            entity: string;
            /** Id */
            id: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** SyncPush */
        SyncPush: {
            /**
             * Cursor
             * @default 0
             */
            cursor: number;
            /** Sessions */
            sessions?: components["schemas"]["SessionIn"][];
            /** Set Logs */
            set_logs?: components["schemas"]["SetLogIn"][];
            /** Body Weights */
            body_weights?: components["schemas"]["BodyWeightIn"][];
            /** Treadmill Sessions */
            treadmill_sessions?: components["schemas"]["TreadmillIn"][];
        };
        /** SyncReject */
        SyncReject: {
            /** Entity */
            entity: string;
            /** Id */
            id: string;
            /** Reason */
            reason: string;
        };
        /** SyncResult */
        SyncResult: {
            /** Cursor */
            cursor: number;
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: components["schemas"]["SyncReject"][];
            /** Events */
            events: components["schemas"]["SyncEventOut"][];
        };
        /** TodayOut */
        TodayOut: {
            /** Next Position */
            next_position: number;
            /** Last Session At */
            last_session_at: string | null;
            day: components["schemas"]["RoutineDayOut"];
        };
        /** TreadmillIn */
        TreadmillIn: {
            /** Id */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Duration S */
            duration_s: number;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VolumeGroup
         * @description Effective (non-voided) working sets for a movement pattern in the last 7
         *     days (spec §7.1; useful range 10-20 per group).
         */
        VolumeGroup: {
            pattern: components["schemas"]["MovementPattern"];
            /** Sets */
            sets: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_exercises_exercises_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"][];
                };
            };
        };
    };
    get_exercise_exercises__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alternatives_exercises__exercise_id__alternatives_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlternativeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_me_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateOut"];
                };
            };
        };
    };
    get_routine_me_routine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
        };
    };
    get_today_me_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayOut"];
                };
            };
        };
    };
    get_bodyweight_me_bodyweight_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyWeightSummary"];
                };
            };
        };
    };
    get_history_me_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
        };
    };
    get_export_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_volume_me_volume_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumeGroup"][];
                };
            };
        };
    };
    get_records_me_records_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordOut"][];
                };
            };
        };
    };
    remove_exercise_me_routine_exercises__rde_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rde_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_exercise_me_routine_exercises__rde_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rde_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_exercise_me_routine_days__day_id__exercises_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_exercises_me_routine_days__day_id__exercise_order_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_day_me_routine_days__day_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DayRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_days_me_routine_day_order_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncPush"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
