/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_exercises_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise */
        get: operations["get_exercise_exercises__exercise_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exercise_id}/alternatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alternatives */
        get: operations["get_alternatives_exercises__exercise_id__alternatives_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State */
        get: operations["get_state_me_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/routine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Routine */
        get: operations["get_routine_me_routine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Today */
        get: operations["get_today_me_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Skip Session */
        post: operations["skip_session_me_skip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/day/{day_id}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Suggestions */
        get: operations["get_suggestions_me_day__day_id__suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/bodyweight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bodyweight */
        get: operations["get_bodyweight_me_bodyweight_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_me_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Export */
        get: operations["get_export_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/exercises/{exercise_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise History */
        get: operations["get_exercise_history_me_exercises__exercise_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Volume */
        get: operations["get_volume_me_volume_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Records */
        get: operations["get_records_me_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Home
         * @description Everything the Inicio tab shows, in one request (one round trip offline).
         *
         *     `period` selects the window for the totals: 7d, 30d, 365d or all.
         */
        get: operations["get_home_me_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/treadmill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Treadmill */
        get: operations["get_treadmill_me_treadmill_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/lab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lab
         * @description Recovery per muscle, recent load, and how much history both rest on.
         *
         *     Everything here is derived from logged sets; nothing is measured. The parts
         *     that need more history than exists come back as null so the screen can say
         *     "not yet" rather than print a number that means nothing.
         */
        get: operations["lab_me_lab_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["read_me_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_me_notifications_patch"];
        trace?: never;
    };
    "/me/notifications/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subscribe */
        post: operations["subscribe_me_notifications_subscribe_post"];
        /** Unsubscribe */
        delete: operations["unsubscribe_me_notifications_subscribe_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/phases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["read_me_phases_get"];
        put?: never;
        /** Start */
        post: operations["start_me_phases_post"];
        /** Finish */
        delete: operations["finish_me_phases_delete"];
        options?: never;
        head?: never;
        /**
         * Toggle
         * @description Turning the feature off closes any running phase rather than leaving it
         *     ticking invisibly, so re-enabling never resurrects a stale one.
         */
        patch: operations["toggle_me_phases_patch"];
        trace?: never;
    };
    "/me/phases/advice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advice
         * @description Propose a rate from two questions, and check a target date against it.
         *
         *     Deliberately deterministic: the same answers always give the same number, so
         *     the reason can be shown and argued with. Nothing is stored.
         */
        post: operations["advice_me_phases_advice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/phases/assessment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assess
         * @description Suggest which phase to run, how fast and for how long.
         *
         *     Deterministic and stateless: the same answers always give the same plan, so
         *     the reasons can be shown and argued with. The user still decides.
         */
        post: operations["assess_me_phases_assessment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/routine/exercises/{rde_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Exercise */
        delete: operations["remove_exercise_me_routine_exercises__rde_id__delete"];
        options?: never;
        head?: never;
        /** Update Exercise */
        patch: operations["update_exercise_me_routine_exercises__rde_id__patch"];
        trace?: never;
    };
    "/me/routine/days/{day_id}/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Exercise */
        post: operations["add_exercise_me_routine_days__day_id__exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/routine/days/{day_id}/exercise-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder Exercises */
        put: operations["reorder_exercises_me_routine_days__day_id__exercise_order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/routine/days/{day_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename Day */
        patch: operations["rename_day_me_routine_days__day_id__patch"];
        trace?: never;
    };
    "/me/routine/day-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder Days */
        put: operations["reorder_days_me_routine_day_order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/routine/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["list_profiles_me_routine_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/routine/profiles/{routine_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Profile */
        post: operations["activate_profile_me_routine_profiles__routine_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/routine/profiles/{routine_id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate Profile */
        post: operations["duplicate_profile_me_routine_profiles__routine_id__duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/routine/profiles/{routine_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Profile */
        delete: operations["delete_profile_me_routine_profiles__routine_id__delete"];
        options?: never;
        head?: never;
        /** Rename Profile */
        patch: operations["rename_profile_me_routine_profiles__routine_id__patch"];
        trace?: never;
    };
    "/me/routine/profiles/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Default
         * @description Copy the untouched seeded routine into a new active profile. The routine
         *     in use is kept as a profile, so restoring is itself reversible.
         */
        post: operations["restore_default_me_routine_profiles_restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/routine/assistant/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review
         * @description Read the routine and say what is worth changing.
         *
         *     Writes nothing. Every finding names a specific exercise in a specific
         *     session, and the ones that depend on history stay quiet until there is
         *     enough of it.
         */
        post: operations["review_me_routine_assistant_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/routine/assistant/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview
         * @description Exactly what would change, before anything does. Same review the apply
         *     runs, so what she confirms is what she gets.
         */
        post: operations["preview_me_routine_assistant_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/routine/assistant/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply
         * @description Apply the ticked findings, after copying the routine to a dated profile.
         *
         *     The request carries only ids; the edits themselves are recomputed here, so a
         *     client can never ask for a change the assistant did not propose.
         */
        post: operations["apply_me_routine_assistant_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/routine/assistant/restructure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restructure
         * @description Build the redistributed split as a new profile and switch to it. The
         *     routine she had stays untouched, just no longer active.
         */
        post: operations["restructure_me_routine_assistant_restructure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityPoint
         * @description One bucket of the activity chart: a day for short windows, a month for
         *     long ones. `sessions` is 0 on rest days, which the chart draws as a gap.
         */
        ActivityPoint: {
            /**
             * Bucket
             * Format: date
             */
            bucket: string;
            /** Sessions */
            sessions: number;
            /** Volume Kg */
            volume_kg: number;
        };
        /**
         * AlternativeOut
         * @description A same-pattern swap candidate (spec §5.3). `substitution_count` is how
         *     often this user has already swapped the planned exercise for this one.
         */
        AlternativeOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            pattern: components["schemas"]["MovementPattern"];
            equipment: components["schemas"]["Equipment"];
            /** Media Url */
            media_url?: string | null;
            /**
             * Per Side
             * @default false
             */
            per_side: boolean;
            /** Substitution Count */
            substitution_count: number;
            /** Default Rest S */
            default_rest_s: number;
        };
        /**
         * AssessmentIn
         * @description Seven answers. All optional: a partial questionnaire still yields a plan,
         *     it is just built on the safer defaults.
         */
        AssessmentIn: {
            /** Objetivo */
            objetivo?: string | null;
            /** Grasa */
            grasa?: string | null;
            /** Experiencia */
            experiencia?: string | null;
            /** Dieta Reciente */
            dieta_reciente?: string | null;
            /** Fecha */
            fecha?: string | null;
            /** Prioridad */
            prioridad?: string | null;
            /** Energia */
            energia?: string | null;
        };
        /**
         * AssessmentOut
         * @description A suggested plan, plus the reasoning as keys the UI writes out. Nothing is
         *     stored: it is a template the user may accept, edit or ignore.
         */
        AssessmentOut: {
            kind: components["schemas"]["PhaseKind"];
            /** Rate Pct */
            rate_pct: number;
            /** Weeks */
            weeks: number;
            /** Reasons */
            reasons: string[];
            /**
             * Suggested Target Date
             * Format: date
             */
            suggested_target_date: string;
        };
        /** BodyWeightIn */
        BodyWeightIn: {
            /** Id */
            id: string;
            /**
             * Measured On
             * Format: date
             */
            measured_on: string;
            /** Weight Kg */
            weight_kg: number;
        };
        /** BodyWeightPoint */
        BodyWeightPoint: {
            /**
             * Measured On
             * Format: date
             */
            measured_on: string;
            /** Weight Kg */
            weight_kg: number;
        };
        /**
         * BodyWeightSummary
         * @description 7-day moving average is the only accionable value (spec §5.6); the raw
         *     latest is exposed only for the treadmill estimate (spec §5.5).
         */
        BodyWeightSummary: {
            /** Latest */
            latest: number | null;
            /** Avg7 */
            avg7: number | null;
            /** Delta Week */
            delta_week: number | null;
            /** Points */
            points: components["schemas"]["BodyWeightPoint"][];
        };
        /** ChangeOut */
        ChangeOut: {
            /** Kind */
            kind: string;
            /** Day */
            day: string;
            /** Exercise */
            exercise: string;
            /** Before */
            before: string;
            /** After */
            after: string;
        };
        /**
         * ConfidenceOut
         * @description How much history the readings above rest on. Shown next to them rather
         *     than kept internal: a number is worth less when it comes from two weeks.
         */
        ConfidenceOut: {
            /** Sessions */
            sessions: number;
            /** Baseline Days */
            baseline_days: number;
            /** Solid */
            solid: boolean;
        };
        /** DayRename */
        DayRename: {
            /** Name */
            name: string;
        };
        /**
         * Equipment
         * @enum {string}
         */
        Equipment: "barra" | "mancuernas" | "maquina" | "polea" | "peso_corporal" | "banda";
        /** ExerciseAdd */
        ExerciseAdd: {
            /** Exercise Id */
            exercise_id: string;
            /**
             * Target Sets
             * @default 3
             */
            target_sets: number;
            /**
             * Rep Min
             * @default 8
             */
            rep_min: number;
            /**
             * Rep Max
             * @default 12
             */
            rep_max: number;
        };
        /**
         * ExerciseHistoryEntry
         * @description The top set of an exercise per past session (spec pantalla 3).
         */
        ExerciseHistoryEntry: {
            /**
             * Session On
             * Format: date
             */
            session_on: string;
            /** Weight Kg */
            weight_kg: number;
            /** Reps */
            reps: number;
        };
        /** ExerciseOut */
        ExerciseOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            pattern: components["schemas"]["MovementPattern"];
            equipment: components["schemas"]["Equipment"];
            /** Media Url */
            media_url?: string | null;
            /**
             * Per Side
             * @default false
             */
            per_side: boolean;
            /** Description */
            description: string;
            /** Default Rest S */
            default_rest_s: number;
            /** Technique */
            technique?: string[];
            /** Mistakes */
            mistakes?: string[];
        };
        /** ExerciseSummary */
        ExerciseSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            pattern: components["schemas"]["MovementPattern"];
            equipment: components["schemas"]["Equipment"];
            /** Media Url */
            media_url?: string | null;
            /**
             * Per Side
             * @default false
             */
            per_side: boolean;
        };
        /** ExerciseUpdate */
        ExerciseUpdate: {
            /** Target Sets */
            target_sets: number;
            /** Rep Min */
            rep_min: number;
            /** Rep Max */
            rep_max: number;
            /** Rest S */
            rest_s: number | null;
        };
        /**
         * FeasibilityOut
         * @description Whether the date and the weight can both be true. Arithmetic, not opinion.
         */
        FeasibilityOut: {
            /** Weeks */
            weeks: number;
            /** Required Rate Pct */
            required_rate_pct: number;
            /** Verdict */
            verdict: string;
            /** Safe Rate Pct */
            safe_rate_pct: number;
            /** Reachable Weight Kg */
            reachable_weight_kg: number | null;
            /** Weeks Needed */
            weeks_needed: number | null;
        };
        /** FindingOut */
        FindingOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Severity */
            severity: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Action Kind */
            action_kind: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HomeOut
         * @description Rolling 7-day picture plus what's next. Nulls mean "not measurable".
         */
        HomeOut: {
            /** Period */
            period: string;
            /** Next Position */
            next_position: number;
            /** Next Day Name */
            next_day_name: string;
            /** Next Exercises */
            next_exercises: number;
            /** Week Sessions */
            week_sessions: number;
            /** Week Sets */
            week_sets: number;
            /** Week Volume Kg */
            week_volume_kg: number;
            /** Week Strength Seconds */
            week_strength_seconds: number;
            /** Week Treadmill Seconds */
            week_treadmill_seconds: number;
            /** Week Kcal */
            week_kcal: number | null;
            /** Bodyweight Avg7 */
            bodyweight_avg7: number | null;
            /** Bodyweight Delta Week */
            bodyweight_delta_week: number | null;
            /** Last Session At */
            last_session_at: string | null;
            /** Volume */
            volume: components["schemas"]["VolumeGroup"][];
            /** Records */
            records: components["schemas"]["RecordOut"][];
            /** Milestones */
            milestones: components["schemas"]["Milestone"][];
            /** Activity */
            activity: components["schemas"]["ActivityPoint"][];
            /** Prev Sessions */
            prev_sessions: number | null;
            /** Prev Volume Kg */
            prev_volume_kg: number | null;
            /** Prev Treadmill Seconds */
            prev_treadmill_seconds: number | null;
        };
        /** LabOut */
        LabOut: {
            /** Recovery */
            recovery: components["schemas"]["MuscleRecoveryOut"][] | null;
            /** Overall Percent */
            overall_percent: number | null;
            load: components["schemas"]["LoadOut"] | null;
            confidence: components["schemas"]["ConfidenceOut"];
            today: components["schemas"]["TodayLoadOut"] | null;
            /** Stalled */
            stalled: components["schemas"]["StalledOut"][];
            /** Trend */
            trend: components["schemas"]["MuscleTrendOut"][] | null;
        };
        /** LoadOut */
        LoadOut: {
            /** Ratio */
            ratio: number;
            /** Band */
            band: string;
            /** Acute Sets */
            acute_sets: number;
            /** Chronic Weekly Sets */
            chronic_weekly_sets: number;
        };
        /** LoginIn */
        LoginIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * LoginOut
         * @description Login also returns the JWT in the body so a native client (Capacitor) can
         *     store it and authenticate via `Authorization: Bearer`. Web keeps using the
         *     httpOnly cookie and ignores this field.
         */
        LoginOut: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Token */
            token: string;
        };
        /**
         * Milestone
         * @description An all-time best the 1RM table cannot express (heaviest set, longest
         *     session, longest run). `kind` is a key; the UI supplies the wording.
         */
        Milestone: {
            /** Kind */
            kind: string;
            /** Value */
            value: number;
            /** Unit */
            unit: string;
            /** Detail */
            detail: string | null;
            /** Achieved On */
            achieved_on: string | null;
        };
        /**
         * MovementPattern
         * @enum {string}
         */
        MovementPattern: "empuje_horizontal" | "empuje_vertical" | "tiron_horizontal" | "tiron_vertical" | "cuadriceps" | "cadena_posterior" | "gluteo" | "gemelo" | "deltoides_lateral" | "triceps" | "biceps" | "core" | "abduccion";
        /** MuscleRecoveryOut */
        MuscleRecoveryOut: {
            /** Muscle */
            muscle: string;
            /** Percent */
            percent: number;
            /** Band */
            band: string;
            /** Hours To Fresh */
            hours_to_fresh: number | null;
        };
        /** MuscleTrendOut */
        MuscleTrendOut: {
            /** Muscle */
            muscle: string;
            /** Weekly */
            weekly: number[];
            /** Trend */
            trend: string;
        };
        /** MuscleVolumeOut */
        MuscleVolumeOut: {
            /** Muscle */
            muscle: string;
            /** Weekly Sets */
            weekly_sets: number;
            /** Band */
            band: string;
        };
        /** NotificationIn */
        NotificationIn: {
            /** Enabled */
            enabled: boolean;
            /** Hour */
            hour: number;
            /** Minute */
            minute: number;
        };
        /** NotificationOut */
        NotificationOut: {
            /** Enabled */
            enabled: boolean;
            /** Hour */
            hour: number;
            /** Minute */
            minute: number;
            /** Vapid Public Key */
            vapid_public_key: string;
            /** Devices */
            devices: number;
        };
        /** OrderBody */
        OrderBody: {
            /** Ids */
            ids: string[];
        };
        /** PhaseAdviceIn */
        PhaseAdviceIn: {
            kind: components["schemas"]["PhaseKind"];
            /** Training Age */
            training_age?: string | null;
            /** Fat Level */
            fat_level?: string | null;
            /** Target Weight Kg */
            target_weight_kg?: number | null;
            /** Target Date */
            target_date?: string | null;
        };
        /** PhaseAdviceOut */
        PhaseAdviceOut: {
            /** Recommended Rate Pct */
            recommended_rate_pct: number;
            /** Rationale */
            rationale: string;
            /** Current Weight Kg */
            current_weight_kg: number | null;
            feasibility: components["schemas"]["FeasibilityOut"] | null;
        };
        /** PhaseIn */
        PhaseIn: {
            kind: components["schemas"]["PhaseKind"];
            /** Target Rate Pct */
            target_rate_pct?: number | null;
            /** Target Date */
            target_date?: string | null;
            /** Target Weight Kg */
            target_weight_kg?: number | null;
        };
        /**
         * PhaseKind
         * @description What the body weight is meant to be doing. The app never causes any of
         *     these — diet does — it only measures whether the outcome matches the
         *     intent and adapts what it expects from training.
         * @enum {string}
         */
        PhaseKind: "superavit" | "definicion" | "mantenimiento";
        /**
         * PhaseLimits
         * @description What the UI may offer for each phase, straight from the guidelines.
         */
        PhaseLimits: {
            kind: components["schemas"]["PhaseKind"];
            /** Min Rate Pct */
            min_rate_pct: number;
            /** Default Rate Pct */
            default_rate_pct: number;
            /** Max Rate Pct */
            max_rate_pct: number;
            /** Suggest End Weeks */
            suggest_end_weeks: number | null;
        };
        /** PhaseOut */
        PhaseOut: {
            /** Id */
            id: string;
            kind: components["schemas"]["PhaseKind"];
            /**
             * Started On
             * Format: date
             */
            started_on: string;
            /** Ended On */
            ended_on: string | null;
            /** Target Rate Pct */
            target_rate_pct: number;
            /** Target Date */
            target_date: string | null;
            /** Target Weight Kg */
            target_weight_kg: number | null;
            status: components["schemas"]["PhaseStatus"] | null;
        };
        /**
         * PhaseStatus
         * @description How the phase is actually going. `verdict` and `duration` are keys the UI
         *     translates; nulls mean "not enough weigh-ins to say", never zero.
         */
        PhaseStatus: {
            /** Weeks Elapsed */
            weeks_elapsed: number;
            /** Measurements */
            measurements: number;
            /** Actual Rate Pct */
            actual_rate_pct: number | null;
            /** Verdict */
            verdict: string;
            /** Duration */
            duration: string;
            /** Suggest End Weeks */
            suggest_end_weeks: number | null;
            /** Days To Target */
            days_to_target: number | null;
        };
        /** PhasesOut */
        PhasesOut: {
            /** Enabled */
            enabled: boolean;
            current: components["schemas"]["PhaseOut"] | null;
            /** History */
            history: components["schemas"]["PhaseOut"][];
            /** Limits */
            limits: components["schemas"]["PhaseLimits"][];
        };
        /** PhasesToggle */
        PhasesToggle: {
            /** Enabled */
            enabled: boolean;
        };
        /** ProfileName */
        ProfileName: {
            /** Name */
            name: string;
        };
        /** PushKeys */
        PushKeys: {
            /** P256Dh */
            p256dh: string;
            /** Auth */
            auth: string;
        };
        /** PushSubscriptionIn */
        PushSubscriptionIn: {
            /** Endpoint */
            endpoint: string;
            keys: components["schemas"]["PushKeys"];
        };
        /**
         * RecordOut
         * @description Personal record per exercise: best estimated 1RM (Epley, spec §7.2).
         */
        RecordOut: {
            /** Exercise Id */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string;
            /** Weight Kg */
            weight_kg: number;
            /** Reps */
            reps: number;
            /** One Rm */
            one_rm: number;
            /**
             * Achieved On
             * Format: date
             */
            achieved_on: string;
        };
        /**
         * RestructureOut
         * @description A different split built from the same exercises. `fits` false means the
         *     work does not go into the time available, which is said rather than hidden.
         */
        RestructureOut: {
            /** Days Per Week */
            days_per_week: number;
            /** Sessions */
            sessions: components["schemas"]["RestructureSessionOut"][];
            /** Trimmed */
            trimmed: {
                [key: string]: unknown;
            }[];
            /** Fits */
            fits: boolean;
            /** Under Target */
            under_target: string[];
            /** Sets Before */
            sets_before: number;
            /** Sets After */
            sets_after: number;
        };
        /** RestructureSessionOut */
        RestructureSessionOut: {
            /** Name */
            name: string;
            /** Total Sets */
            total_sets: number;
            /** Minutes */
            minutes: number;
            /** Exercises */
            exercises: string[];
        };
        /** RoutineApplyIn */
        RoutineApplyIn: {
            answers: components["schemas"]["RoutineReviewIn"];
            /**
             * Accepted
             * @default []
             */
            accepted: string[];
        };
        /** RoutineApplyOut */
        RoutineApplyOut: {
            /** Changed */
            changed: number;
            /** Snapshot */
            snapshot: string | null;
        };
        /** RoutineDayExerciseOut */
        RoutineDayExerciseOut: {
            /** Id */
            id: string;
            /** Order Index */
            order_index: number;
            /** Target Sets */
            target_sets: number;
            /** Rep Min */
            rep_min: number;
            /** Rep Max */
            rep_max: number;
            /** Rest S */
            rest_s: number;
            /**
             * Unit
             * @default reps
             */
            unit: string;
            exercise: components["schemas"]["ExerciseSummary"];
        };
        /** RoutineDayOut */
        RoutineDayOut: {
            /** Id */
            id: string;
            /** Position */
            position: number;
            /** Name */
            name: string;
            /** Suggested Dow */
            suggested_dow: number | null;
            /** Exercises */
            exercises: components["schemas"]["RoutineDayExerciseOut"][];
        };
        /** RoutineOut */
        RoutineOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Active */
            active: boolean;
            /** Days */
            days: components["schemas"]["RoutineDayOut"][];
        };
        /** RoutineProfileOut */
        RoutineProfileOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Active */
            active: boolean;
            /** Is Original */
            is_original: boolean;
            /** Days */
            days: number;
            /** Sessions */
            sessions: number;
            /** Can Delete */
            can_delete: boolean;
        };
        /**
         * RoutineReviewIn
         * @description The five things the routine cannot tell us. All optional: a partial
         *     questionnaire still yields a review, built on the safer defaults.
         */
        RoutineReviewIn: {
            /** Dias */
            dias?: number | null;
            /** Tiempo */
            tiempo?: string | null;
            /** Objetivo */
            objetivo?: string | null;
            /** Evitar */
            evitar?: string | null;
            /**
             * Prioridad
             * @default []
             */
            prioridad: string[];
        };
        /** RoutineReviewOut */
        RoutineReviewOut: {
            /** Days Per Week */
            days_per_week: number;
            /** Volumes */
            volumes: components["schemas"]["MuscleVolumeOut"][];
            /** Session Minutes */
            session_minutes: components["schemas"]["SessionLengthOut"][];
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            restructure: components["schemas"]["RestructureOut"] | null;
        };
        /** SessionIn */
        SessionIn: {
            /** Id */
            id: string;
            /** Routine Day Id */
            routine_day_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** @default in_progress */
            status: components["schemas"]["SessionStatus"];
            /** Notes */
            notes?: string | null;
        };
        /** SessionLengthOut */
        SessionLengthOut: {
            /** Name */
            name: string;
            /** Minutes */
            minutes: number;
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: string;
            /** Routine Day Id */
            routine_day_id: string;
            /** Position */
            position: number;
            /** Day Name */
            day_name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            status: components["schemas"]["SessionStatus"];
            /** Notes */
            notes: string | null;
            /**
             * Set Count
             * @default 0
             */
            set_count: number;
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "in_progress" | "completed" | "abandoned";
        /** SetLogIn */
        SetLogIn: {
            /** Id */
            id: string;
            /** Session Id */
            session_id: string;
            /** Exercise Id */
            exercise_id: string;
            /** Planned Exercise Id */
            planned_exercise_id?: string | null;
            /** Set Number */
            set_number: number;
            /** Weight Kg */
            weight_kg: number;
            /** Reps */
            reps: number;
            /**
             * Voided
             * @default false
             */
            voided: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StalledOut */
        StalledOut: {
            /** Exercise Id */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string;
            /** Sessions */
            sessions: number;
            /** Days Since Best */
            days_since_best: number;
        };
        /** StateOut */
        StateOut: {
            /** Routine Id */
            routine_id: string;
            /** Next Position */
            next_position: number;
            /** Last Session At */
            last_session_at: string | null;
        };
        /** Suggestion */
        Suggestion: {
            /** Exercise Id */
            exercise_id: string;
            /** Last Weight Kg */
            last_weight_kg: number | null;
            /** Last Reps */
            last_reps: number[];
            /** All At Rep Max */
            all_at_rep_max: boolean;
            /** Suggested Weight Kg */
            suggested_weight_kg: number | null;
            /** Last Session On */
            last_session_on: string | null;
        };
        /** SyncEventOut */
        SyncEventOut: {
            /** Seq */
            seq: number;
            /** Entity */
            entity: string;
            /** Id */
            id: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** SyncPush */
        SyncPush: {
            /**
             * Cursor
             * @default 0
             */
            cursor: number;
            /** Sessions */
            sessions?: components["schemas"]["SessionIn"][];
            /** Set Logs */
            set_logs?: components["schemas"]["SetLogIn"][];
            /** Body Weights */
            body_weights?: components["schemas"]["BodyWeightIn"][];
            /** Treadmill Sessions */
            treadmill_sessions?: components["schemas"]["TreadmillIn"][];
        };
        /** SyncReject */
        SyncReject: {
            /** Entity */
            entity: string;
            /** Id */
            id: string;
            /** Reason */
            reason: string;
        };
        /** SyncResult */
        SyncResult: {
            /** Cursor */
            cursor: number;
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: components["schemas"]["SyncReject"][];
            /** Events */
            events: components["schemas"]["SyncEventOut"][];
        };
        /**
         * TodayLoadOut
         * @description What the session the wheel has queued up will actually ask for, against
         *     how recovered those muscles are. The point of the map, made actionable.
         */
        TodayLoadOut: {
            /** Day Name */
            day_name: string;
            /** Position */
            position: number;
            /** Muscles */
            muscles: components["schemas"]["TodayMuscleOut"][];
            /** Verdict */
            verdict: string;
        };
        /** TodayMuscleOut */
        TodayMuscleOut: {
            /** Muscle */
            muscle: string;
            /** Percent */
            percent: number;
            /** Band */
            band: string;
            /** Sets */
            sets: number;
        };
        /** TodayOut */
        TodayOut: {
            /** Next Position */
            next_position: number;
            /** Last Session At */
            last_session_at: string | null;
            day: components["schemas"]["RoutineDayOut"];
            /**
             * Recovery Warning
             * @default false
             */
            recovery_warning: boolean;
            /**
             * Resume After Break
             * @default false
             */
            resume_after_break: boolean;
        };
        /** TreadmillEntry */
        TreadmillEntry: {
            /** Id */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration S */
            duration_s: number;
            /** Kcal */
            kcal: number | null;
        };
        /** TreadmillIn */
        TreadmillIn: {
            /** Id */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Duration S */
            duration_s: number;
        };
        /** TreadmillSummary */
        TreadmillSummary: {
            /** Entries */
            entries: components["schemas"]["TreadmillEntry"][];
            /** Week Seconds */
            week_seconds: number;
            /** Week Kcal */
            week_kcal: number | null;
            /** Total Seconds */
            total_seconds: number;
            /** Sessions */
            sessions: number;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VolumeGroup
         * @description Effective (non-voided) working sets for a movement pattern in the last 7
         *     days (spec §7.1; useful range 10-20 per group).
         */
        VolumeGroup: {
            pattern: components["schemas"]["MovementPattern"];
            /** Sets */
            sets: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_exercises_exercises_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"][];
                };
            };
        };
    };
    get_exercise_exercises__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alternatives_exercises__exercise_id__alternatives_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlternativeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_me_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateOut"];
                };
            };
        };
    };
    get_routine_me_routine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
        };
    };
    get_today_me_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayOut"];
                };
            };
        };
    };
    skip_session_me_skip_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateOut"];
                };
            };
        };
    };
    get_suggestions_me_day__day_id__suggestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suggestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bodyweight_me_bodyweight_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyWeightSummary"];
                };
            };
        };
    };
    get_history_me_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
        };
    };
    get_export_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_exercise_history_me_exercises__exercise_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseHistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_volume_me_volume_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumeGroup"][];
                };
            };
        };
    };
    get_records_me_records_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordOut"][];
                };
            };
        };
    };
    get_home_me_home_get: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_treadmill_me_treadmill_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreadmillSummary"];
                };
            };
        };
    };
    lab_me_lab_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabOut"];
                };
            };
        };
    };
    read_me_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
        };
    };
    update_me_notifications_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subscribe_me_notifications_subscribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscriptionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsubscribe_me_notifications_subscribe_delete: {
        parameters: {
            query: {
                endpoint: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_phases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhasesOut"];
                };
            };
        };
    };
    start_me_phases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhaseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhasesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_me_phases_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhasesOut"];
                };
            };
        };
    };
    toggle_me_phases_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhasesToggle"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhasesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advice_me_phases_advice_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhaseAdviceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhaseAdviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assess_me_phases_assessment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_exercise_me_routine_exercises__rde_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rde_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_exercise_me_routine_exercises__rde_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rde_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_exercise_me_routine_days__day_id__exercises_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_exercises_me_routine_days__day_id__exercise_order_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_day_me_routine_days__day_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DayRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_days_me_routine_day_order_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_me_routine_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineProfileOut"][];
                };
            };
        };
    };
    activate_profile_me_routine_profiles__routine_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineProfileOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_profile_me_routine_profiles__routine_id__duplicate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routine_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileName"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineProfileOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_me_routine_profiles__routine_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineProfileOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_profile_me_routine_profiles__routine_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routine_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileName"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineProfileOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_default_me_routine_profiles_restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineProfileOut"][];
                };
            };
        };
    };
    review_me_routine_assistant_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_me_routine_assistant_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineApplyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_me_routine_assistant_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineApplyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineApplyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restructure_me_routine_assistant_restructure_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineApplyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncPush"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
