"""exercise technique and mistakes

Revision ID: 7feb57db01ae
Revises: b33d377922fc
Create Date: 2026-08-06 19:29:48.957565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7feb57db01ae'
down_revision: Union[str, Sequence[str], None] = 'b33d377922fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technique', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
        batch_op.add_column(sa.Column('mistakes', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('mistakes')
        batch_op.drop_column('technique')

    # ### end Alembic commands ###
