"""phase target weight

Revision ID: 81b4d6cb5bfb
Revises: 8461ddeafbee
Create Date: 2026-08-07 19:02:24.681897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b4d6cb5bfb'
down_revision: Union[str, Sequence[str], None] = '8461ddeafbee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_weight_kg', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.drop_column('target_weight_kg')

    # ### end Alembic commands ###
