"""training phases

Revision ID: 8461ddeafbee
Revises: 7feb57db01ae
Create Date: 2026-08-07 16:49:54.328591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8461ddeafbee'
down_revision: Union[str, Sequence[str], None] = '7feb57db01ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('superavit', 'definicion', 'mantenimiento', name='phasekind', native_enum=False, length=20), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('target_rate_pct', sa.Float(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_phases_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phases'))
    )
    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phases_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phases_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phases_enabled')

    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phases_user_id'))

    op.drop_table('phases')
    # ### end Alembic commands ###
