"""initial schema

Revision ID: cdd4b49e886b
Revises: 
Create Date: 2026-08-04 20:49:11.453863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd4b49e886b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('pattern', sa.Enum('empuje_horizontal', 'empuje_vertical', 'tiron_horizontal', 'tiron_vertical', 'cuadriceps', 'cadena_posterior', 'gluteo', 'gemelo', 'deltoides_lateral', 'triceps', 'biceps', 'core', name='movementpattern', native_enum=False, length=32), nullable=False),
    sa.Column('equipment', sa.Enum('barra', 'mancuernas', 'maquina', 'polea', 'peso_corporal', name='equipment', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('media_url', sa.String(length=255), nullable=True),
    sa.Column('default_rest_s', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('body_weights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('measured_on', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_body_weights_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_weights'))
    )
    with op.batch_alter_table('body_weights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_weights_user_id'), ['user_id'], unique=False)

    op.create_table('exercise_preferences',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('planned_exercise_id', sa.String(length=36), nullable=False),
    sa.Column('preferred_exercise_id', sa.String(length=36), nullable=False),
    sa.Column('substitution_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planned_exercise_id'], ['exercises.id'], name=op.f('fk_exercise_preferences_planned_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['preferred_exercise_id'], ['exercises.id'], name=op.f('fk_exercise_preferences_preferred_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exercise_preferences_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'planned_exercise_id', 'preferred_exercise_id', name=op.f('pk_exercise_preferences'))
    )
    op.create_table('routines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_routines_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routines'))
    )
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routines_user_id'), ['user_id'], unique=False)

    op.create_table('treadmill_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_treadmill_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treadmill_sessions'))
    )
    with op.batch_alter_table('treadmill_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treadmill_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('routine_days',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('routine_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('suggested_dow', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], name=op.f('fk_routine_days_routine_id_routines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routine_days'))
    )
    with op.batch_alter_table('routine_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routine_days_routine_id'), ['routine_id'], unique=False)

    op.create_table('user_state',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('routine_id', sa.String(length=36), nullable=False),
    sa.Column('next_position', sa.Integer(), nullable=False),
    sa.Column('last_session_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], name=op.f('fk_user_state_routine_id_routines')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_state_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_state'))
    )
    op.create_table('routine_day_exercises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('routine_day_id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('rep_min', sa.Integer(), nullable=False),
    sa.Column('rep_max', sa.Integer(), nullable=False),
    sa.Column('rest_s', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_routine_day_exercises_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['routine_day_id'], ['routine_days.id'], name=op.f('fk_routine_day_exercises_routine_day_id_routine_days')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routine_day_exercises'))
    )
    with op.batch_alter_table('routine_day_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routine_day_exercises_routine_day_id'), ['routine_day_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('routine_day_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='sessionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['routine_day_id'], ['routine_days.id'], name=op.f('fk_sessions_routine_day_id_routine_days')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('set_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('planned_exercise_id', sa.String(length=36), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('voided', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_set_logs_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['planned_exercise_id'], ['exercises.id'], name=op.f('fk_set_logs_planned_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_set_logs_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_set_logs'))
    )
    with op.batch_alter_table('set_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_set_logs_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_set_logs_session_id'))

    op.drop_table('set_logs')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('routine_day_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routine_day_exercises_routine_day_id'))

    op.drop_table('routine_day_exercises')
    op.drop_table('user_state')
    with op.batch_alter_table('routine_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routine_days_routine_id'))

    op.drop_table('routine_days')
    with op.batch_alter_table('treadmill_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treadmill_sessions_user_id'))

    op.drop_table('treadmill_sessions')
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routines_user_id'))

    op.drop_table('routines')
    op.drop_table('exercise_preferences')
    with op.batch_alter_table('body_weights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_weights_user_id'))

    op.drop_table('body_weights')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('exercises')
    # ### end Alembic commands ###
